project_id = "itghsdpzvjvxiqbyfcpn"

[functions.business-discovery]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = false

[functions.email-generation]
verify_jwt = false

[functions.generate-action-plan]
verify_jwt = false

[functions.detailed-report]
verify_jwt = false